config/routes.rb
Rails.application.routes.draw do

  

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'
  get 'dashboard' => 'static_pages#dashboard'
  get 'contact' => 'static_pages#contact'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token

	before_save { self.email = email.downcase }
	validates(:first_name, presence: true, length: {maximum: 35})
	validates(:last_name, presence: true, length: {maximum: 35})
	VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, 
			   format: { with: VALID_EMAIL_REGEX }, 
			   uniqueness: {case_sensitive: false}

	has_secure_password
	validates(:password, presence: true, length: {minimum:6})

	  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

    # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
  	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

    # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
		log_in user
		redirect_to user		
  	else
  		#create an error message
  		flash.now[:danger] = 'Email y/o Contraseña incorrectos' 
  		render 'new'
  	end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def dashboard
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
    if @user.save
      log_in @user
      remember @user
      flash[:success] = "Bienvenido a Taza!"
      redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
		base_title = "Taza"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end

	end
end

app/helpers/sessions_helper.rb
module SessionsHelper


	# Logs in the given user
	def log_in(user)
		session[:user_id] = user.id
	end

	# Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

	# Returns de current logged in user (if any)
	def current_user
  		if (user_id = session[:user_id])
   			@current_user ||= User.find_by(id: user_id)
  		elsif (user_id = cookies.signed[:user_id])
    		user = User.find_by(id: user_id)
    		if user && user.authenticated?(cookies[:remember_token])
      			log_in user
      		@current_user = user
    		end
  		end
	end

    # Returns true if the user is logged in, false otherwise
    def logged_in?
    	!current_user.nil?
    end
	  # Forgets a persistent session.
	  def forget(user)
	    user.forget
	    cookies.delete(:user_id)
	    cookies.delete(:remember_token)
	  end

    def log_out
    	forget(current_user)
    	session.delete(:user_id)
    	@current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="">
	<footer class="">
		<ul class="container-fluid">
			<%= link_to "<li>About</li>".html_safe, about_path, class: "footer-ul" %>
			<%= link_to "<li>Help</li>".html_safe, help_path, class: "footer-ul" %>
			<%= link_to "<li>Contact</li>".html_safe, contact_path, class: "footer-ul" %>
		</ul>
		<!--<div>Taza Corp 2015</div>-->
	</footer>
</div>

app/views/layouts/_header.html.erb
<div class="">
		<header>
			<nav class="navbar navbar-default navbar-static-top">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed navbar-header-form-btn" data-toggle="collapse" data-target="#navbar-1" aria-expanded="false">
							<span class="sr-only">Menu</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
							<%= link_to (image_tag("logo 2.0.png", class: "navbar-header-img navbar-header-img", height: "50")), root_path, class: "navbar-brand" %>
					</div>

					<div class="collapse navbar-collapse navbar-collapse-correction" id="navbar-1">
						<% if logged_in? %>
							<div class="row">
								<div class="col-xs-5 col-xs-offset-1 col-sm-4 col-sm-offset- col-md-5 col-md-offset-1 col-xl-5 col-xl-offset-1">
									<ul class="nav navbar-nav navbar-header-ul header-ul btn-full-width text-center full-height">
										<li><%= link_to "Dashboard", '#', class: "header-ul" %></li>
										<li><%= link_to "Actividades", '#', class: "header-ul" %></li>
										<li><%= link_to "Contacto", '#', class: "header-ul" %></li>
								    </ul>
								</div>
								<div class="col-xs-2 col-xs-offset-1 col-sm-3 col-sm-offset-0 col-md-2 col-md-offset-1 col-xl-2 col-xl-offset-1">
									<ul class="nav navbar-nav navbar-header-ul header-ul btn-full-width text-center full-height">
										<li class="dropdown header-ul">
								            <a href="#" class="dropdown-toggle align-right" data-toggle="dropdown">
								              <%= @user.first_name %> <%= @user.last_name %> <b class="caret"></b>
								            </a>
								            <ul class="dropdown-menu">
								              <li><%= link_to "Profile", current_user %></li>
								              <li><%= link_to "Settings", '#' %></li>
								              <li class="divider"></li>
								              <li>
								                <%= link_to "Log out", logout_path, method: "delete" %>
								              </li>
								            </ul>
								        </li>
									</ul>
								</div>

							</div>
						<% else %>

							<%= form_for(:session, url: login_path, :html => {:class => "navbar-form navbar-right navbar-header-form"}) do |f| %>
								<div class="form-group">
							      <%= f.email_field :email, class: 'form-control form-control-correction input-sm', placeholder: 'Email' %>
								</div>
								<div class="form-group">
							      <%= f.password_field :password, class: 'form-control form-control-correction input-sm', placeholder: 'Password' %>
								</div>
							      <%= f.submit "Log in", class: "btn btn-default navbar-btn btn-sm navbar-form-btn btn-correction" %>
							<% end %>
						<% end %>

					</div>
				</div>
			</nav>
		</header>
	</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

</head>
<body>
	<%= render 'layouts/header' %>
		<div class="container container-flash">
			<% flash.each do |message_type, message| %>
        	<div class="alert alert-<%= message_type %>"><%= message %></div>
      		<% end %>
      	</div>

<%= yield %>

	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam beatae eos facilis eveniet explicabo ut cumque, nulla minus tempore impedit enim voluptatibus quod, quisquam aliquam ea culpa ex eaque qui!</p>

app/views/static_pages/dashboard.html.erb
<% provide(:title, "Dashboard") %>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Incidunt reprehenderit, neque iste, voluptatem debitis reiciendis autem architecto ratione consequatur aliquid sint cupiditate nisi rem nesciunt quos atque labore sapiente. Expedita!</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
	<div class="container">
		<div class="jumbotron">
					<h2>Bienvenido a Taza</h2>
					<p>El sitio donde se generan nuevos vínculos sociales a través de actividades, y a la vez, se promueven nuevas actividades mediante la motivación a generar nuevos vínculos sociales.</p>
					<%= link_to "Registrate", signup_path, class: "btn btn-primary btn-orange btn-lg navbar-form-btn" %>
					
		</div>
	</div>

	<div class="container">
		<div class="jumbotron">
			<div id="carousel-1" class="carousel slide" data-ride="carousel">
				<!-- Inidicadores -->
				<ol class="carousel-indicators">
					<li data-target="#carousel-1" data-slide-to="0" class="active"></li>
					<li data-target="#carousel-1" data-slide-to="1"></li>
					<li data-target="#carousel-1" data-slide-to="2"></li>
				</ol>

				<!--contenedor de los slides -->
				<div class="carousel-inner" role="listbox">
					<div class="item active">
						<%= image_tag("PaintballCarousel.jpg", class: "img-responsive img-rounded") %>
						<div class="carousel-caption">
							<h3>Paintball</h3>
						</div>
					</div>
					<div class="item">
						<%= image_tag("BungeeCarousel.jpg", class: "img-responsive img-rounded") %>
						<div class="carousel-caption">
							<h3>Bungee</h3>
						</div>
					</div>
					<div class="item">
						<%= image_tag("FiestaCarousel.jpg", class: "img-responsive img-rounded") %>
						<div class="carousel-caption">
							<h3>Fiesta</h3>
						</div>
					</div>
				</div>
				<a href="#carousel-1" class="left carousel-control" role="button" data-slide="prev">
					<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
					<span class="sr-only">Anterior</span>
				</a>
				<a href="#carousel-1" class="right carousel-control" role="button" data-slide="next">
					<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
					<span class="sr-only">Siguiente</span>
				</a>
			</div>
		</div>
	</div>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<div class="container">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-8 col-lg-offset-2">
				<div class="jumbotron">
					<div class="row">
						<div class="col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1">
							<h2>Registrate en Taza</h2>
								<%= form_for(@user) do |f| %>
									<%= render 'shared/error_messages' %>

									<div class="form-group">
								      <%= f.label :first_name, "Nombre" %>
								      <%= f.text_field :first_name , class: 'form-control' %>
									</div>
									<div class="form-group">
								      <%= f.label :last_name, "Apellido" %>
								      <%= f.text_field :last_name , class: 'form-control' %>
									</div>
									<div class="form-group">
								      <%= f.label :email, "Email" %>
								      <%= f.email_field :email , class: 'form-control' %>
									</div>
									<div class="form-group">
								      <%= f.label :password, "Contraseña" %>
								      <%= f.password_field :password , class: 'form-control' %>
									</div>
									<div class="form-group">
								      <%= f.label :password_confirmation, "Confirmar Contraseña" %>
								      <%= f.password_field :password_confirmation , class: 'form-control' %>
									</div>
									
							      <%= f.submit "Submit", class: "btn btn-default btn-lg btn-orange btn-block" %>
								<% end %>
								
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.first_name} #{@user.last_name}") %>
<div class="container">
	<div class="jumbotron">
				<h2><%= @user.first_name %> <%= @user.last_name %></h2>
				<p><%= @user.email %></p>
				
	</div>
</div>